{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPot8erC8Ir6WEvQGtt315f"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["!pip install experta"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3uAAKnvZnSXl","executionInfo":{"status":"ok","timestamp":1744773664078,"user_tz":-420,"elapsed":5324,"user":{"displayName":"JACK minss","userId":"15250300980242217565"}},"outputId":"5441fa00-fef5-4b20-86e7-97c5cd627749"},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting experta\n","  Downloading experta-1.9.4-py3-none-any.whl.metadata (5.0 kB)\n","Collecting frozendict==1.2 (from experta)\n","  Downloading frozendict-1.2.tar.gz (2.6 kB)\n","  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Collecting schema==0.6.7 (from experta)\n","  Downloading schema-0.6.7-py2.py3-none-any.whl.metadata (14 kB)\n","Downloading experta-1.9.4-py3-none-any.whl (35 kB)\n","Downloading schema-0.6.7-py2.py3-none-any.whl (14 kB)\n","Building wheels for collected packages: frozendict\n","  Building wheel for frozendict (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for frozendict: filename=frozendict-1.2-py3-none-any.whl size=3149 sha256=b8b1c958ec7e609b8d2b0166678c6c3a513d0dd4925b63083e4e2d55648a0d89\n","  Stored in directory: /root/.cache/pip/wheels/49/ac/f8/cb8120244e710bdb479c86198b03c7b08c3c2d3d2bf448fd6e\n","Successfully built frozendict\n","Installing collected packages: schema, frozendict, experta\n","  Attempting uninstall: frozendict\n","    Found existing installation: frozendict 2.4.6\n","    Uninstalling frozendict-2.4.6:\n","      Successfully uninstalled frozendict-2.4.6\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","yfinance 0.2.55 requires frozendict>=2.3.4, but you have frozendict 1.2 which is incompatible.\u001b[0m\u001b[31m\n","\u001b[0mSuccessfully installed experta-1.9.4 frozendict-1.2 schema-0.6.7\n"]}]},{"cell_type":"code","source":["!pip install --upgrade frozendict experta"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"KPA-PRQxnWl8","executionInfo":{"status":"ok","timestamp":1744773678747,"user_tz":-420,"elapsed":3814,"user":{"displayName":"JACK minss","userId":"15250300980242217565"}},"outputId":"3810f058-a1b1-4a80-8b24-f6ae9985d262"},"execution_count":3,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: frozendict in /usr/local/lib/python3.11/dist-packages (1.2)\n","Collecting frozendict\n","  Downloading frozendict-2.4.6-py311-none-any.whl.metadata (23 kB)\n","Requirement already satisfied: experta in /usr/local/lib/python3.11/dist-packages (1.9.4)\n","Requirement already satisfied: schema==0.6.7 in /usr/local/lib/python3.11/dist-packages (from experta) (0.6.7)\n"]}]},{"cell_type":"code","source":["!pip install --upgrade frozendict"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"_B3QqlWgnaPG","executionInfo":{"status":"ok","timestamp":1744773693818,"user_tz":-420,"elapsed":3729,"user":{"displayName":"JACK minss","userId":"15250300980242217565"}},"outputId":"7c826e10-5e58-4e72-ce13-523a64f1a1d4"},"execution_count":4,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: frozendict in /usr/local/lib/python3.11/dist-packages (1.2)\n","Collecting frozendict\n","  Using cached frozendict-2.4.6-py311-none-any.whl.metadata (23 kB)\n","Downloading frozendict-2.4.6-py311-none-any.whl (16 kB)\n","Installing collected packages: frozendict\n","  Attempting uninstall: frozendict\n","    Found existing installation: frozendict 1.2\n","    Uninstalling frozendict-1.2:\n","      Successfully uninstalled frozendict-1.2\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","experta 1.9.4 requires frozendict==1.2, but you have frozendict 2.4.6 which is incompatible.\u001b[0m\u001b[31m\n","\u001b[0mSuccessfully installed frozendict-2.4.6\n"]}]},{"cell_type":"code","source":["from experta import *\n","\n","class Diagnosis(KnowledgeEngine):\n","\n","    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(fatigue=True) & Fact(breathing_difficulty=False))\n","    def flu(self):\n","        print(\"Diagnosis: You may have the Flu.\")\n","\n","    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True) & Fact(fatigue=False))\n","    def pneumonia(self):\n","        print(\"Diagnosis: You may have Pneumonia.\")\n","\n","    @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(cough=False) & Fact(fever=False))\n","    def cold(self):\n","        print(\"Diagnosis: You may have a Common Cold.\")\n","\n","    @Rule(Fact(sore_throat=True) & Fact(fever=True) & Fact(cough=False))\n","    def throat_infection(self):\n","        print(\"Diagnosis: You may have a Throat Infection.\")\n","\n","    @Rule(Fact(cough=True) & Fact(fever=True) & Fact(breathing_difficulty=True) & Fact(fatigue=True))\n","    def covid(self):\n","        print(\"Diagnosis: You may have COVID-19.\")\n","\n","    @Rule(Fact(sneezing=True) & Fact(runny_nose=True) & Fact(fever=False) & Fact(cough=True))\n","    def allergy(self):\n","        print(\"Diagnosis: You may have an Allergy.\")\n","\n","    @Rule(Fact(cough=True) & Fact(fatigue=True) & Fact(fever=False) & Fact(breathing_difficulty=True))\n","    def bronchitis(self):\n","        print(\"Diagnosis: You may have Bronchitis.\")\n","\n","    @Rule(Fact(sore_throat=False) & Fact(fatigue=False) & Fact(runny_nose=True) & Fact(sneezing=False) & Fact(cough=False))\n","    def sinusitis(self):\n","        print(\"Diagnosis: You may have Sinusitis.\")\n","\n","    @Rule(Fact(cough=False) & Fact(fever=False) & Fact(fatigue=False) & Fact(breathing_difficulty=False) &\n","          Fact(sneezing=False) & Fact(runny_nose=False) & Fact(sore_throat=False))\n","    def healthy(self):\n","        print(\"Diagnosis: You seem to be healthy.\")\n","\n","def get_input():\n","    \"\"\"Helper function to get user input as boolean (yes/no).\"\"\"\n","    def ask_question(question):\n","        return input(question + \" (yes/no): \").strip().lower() == \"yes\"\n","\n","    return {\n","        \"cough\": ask_question(\"Do you have a cough?\"),\n","        \"fever\": ask_question(\"Do you have a fever?\"),\n","        \"fatigue\": ask_question(\"Do you feel fatigued?\"),\n","        \"breathing_difficulty\": ask_question(\"Do you have breathing difficulties?\"),\n","        \"sneezing\": ask_question(\"Are you sneezing?\"),\n","        \"runny_nose\": ask_question(\"Do you have a runny nose?\"),\n","        \"sore_throat\": ask_question(\"Do you have a sore throat?\")\n","    }\n","\n","# Running the Expert System\n","if __name__ == \"__main__\":\n","    symptoms = get_input()\n","    engine = Diagnosis()\n","    engine.reset()  # Reset the knowledge engine\n","\n","    for symptom, present in symptoms.items():\n","        engine.declare(Fact(**{symptom: present}))  # Declare facts\n","\n","    engine.run()  # Run the inference engine\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"6BD6WnrlnetF","executionInfo":{"status":"ok","timestamp":1744775289763,"user_tz":-420,"elapsed":13220,"user":{"displayName":"JACK minss","userId":"15250300980242217565"}},"outputId":"08658c9a-ecc3-405c-a9ea-a4772d614365"},"execution_count":14,"outputs":[{"output_type":"stream","name":"stdout","text":["Do you have a cough? (yes/no): no\n","Do you have a fever? (yes/no): no\n","Do you feel fatigued? (yes/no): no\n","Do you have breathing difficulties? (yes/no): no\n","Are you sneezing? (yes/no): no\n","Do you have a runny nose? (yes/no): no\n","Do you have a sore throat? (yes/no): no\n","Diagnosis: You seem to be healthy.\n"]}]}]}